"""
engine/export/pinescript.py
───────────────────────────
Convert Python strategies and backtest results to TradingView Pine Script v5.

Usage:
    from engine.export.pinescript import strategy_to_pinescript, export_backtest_result_to_pinescript

    # From a saved strategy (Python code + metadata)
    pine = strategy_to_pinescript(
        name="my_macd_strategy",
        python_code=code_str,
        metadata={"description": "MACD crossover", "default_symbol": "INFY"},
    )

    # From a backtest result object
    pine = export_backtest_result_to_pinescript(backtest_result)
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any, Optional

# ── Pine Script template pieces ───────────────────────────────

_PINE_HEADER = """\
//@version=5
// Generated by india-trade-cli — {date}
// Strategy: {name}
// {description}

strategy(
    title = "{name}",
    overlay = true,
    initial_capital = 100000,
    default_qty_type = strategy.percent_of_equity,
    default_qty_value = 100,
    commission_type = strategy.commission.percent,
    commission_value = 0.1
)

"""

_PINE_INPUT_BLOCK = """\
// ── Inputs ────────────────────────────────────────────────────
fast_len  = input.int(12,  "Fast Length",  minval=1)
slow_len  = input.int(26,  "Slow Length",  minval=1)
sig_len   = input.int(9,   "Signal Length", minval=1)

"""

_PINE_MACD_LOGIC = """\
// ── MACD Logic ────────────────────────────────────────────────
[macd_line, signal_line, hist] = ta.macd(close, fast_len, slow_len, sig_len)

long_cond  = ta.crossover(macd_line, signal_line)
short_cond = ta.crossunder(macd_line, signal_line)

"""

_PINE_RSI_LOGIC = """\
// ── RSI Logic ─────────────────────────────────────────────────
rsi_len   = input.int(14, "RSI Period", minval=2, maxval=50)
buy_level = input.int(30,  "Buy Level",  minval=10, maxval=49)
sell_level = input.int(70, "Sell Level", minval=51, maxval=90)

rsi_val    = ta.rsi(close, rsi_len)
long_cond  = ta.crossover(rsi_val, buy_level)
short_cond = ta.crossunder(rsi_val, sell_level)

"""

_PINE_BB_LOGIC = """\
// ── Bollinger Bands Logic ─────────────────────────────────────
bb_len = input.int(20, "BB Period",  minval=2)
bb_std = input.float(2.0, "Std Dev", minval=0.1, step=0.1)

[upper, basis, lower] = ta.bb(close, bb_len, bb_std)
long_cond  = ta.crossover(close, lower)
short_cond = ta.crossunder(close, upper)

"""

_PINE_EMA_LOGIC = """\
// ── EMA Crossover Logic ───────────────────────────────────────
fast_ema_len = input.int(9,  "Fast EMA", minval=1)
slow_ema_len = input.int(21, "Slow EMA", minval=1)

fast_ema = ta.ema(close, fast_ema_len)
slow_ema = ta.ema(close, slow_ema_len)

long_cond  = ta.crossover(fast_ema, slow_ema)
short_cond = ta.crossunder(fast_ema, slow_ema)

"""

_PINE_GENERIC_LOGIC = """\
// ── Signal Logic ─────────────────────────────────────────────
// NOTE: Auto-generated from Python strategy — review before use
// Original strategy name: {strategy_name}
// The logic below is a placeholder; adapt to match your Python indicators.

sma_fast = ta.sma(close, 10)
sma_slow = ta.sma(close, 30)

long_cond  = ta.crossover(sma_fast, sma_slow)
short_cond = ta.crossunder(sma_fast, sma_slow)

"""

_PINE_ENTRIES = """\
// ── Entries & Exits ───────────────────────────────────────────
if long_cond
    strategy.entry("Long", strategy.long)

if short_cond
    strategy.close("Long")
    // Uncomment for short selling:
    // strategy.entry("Short", strategy.short)

"""

_PINE_TRADE_MARKERS = """\
// ── Visual Markers ────────────────────────────────────────────
plotshape(long_cond,  title="Buy",  style=shape.triangleup,
          location=location.belowbar, color=color.green, size=size.small)
plotshape(short_cond, title="Sell", style=shape.triangledown,
          location=location.abovebar, color=color.red,   size=size.small)

"""

_PINE_BACKTEST_TRADES = """\
// ── Historical Trades (from backtest) ─────────────────────────
// Imported {n_trades} trades from Python backtest
// Symbol: {symbol} | Period: {period}
// Total Return: {total_return:+.2f}% | Sharpe: {sharpe:.2f} | Win Rate: {win_rate:.1f}%
// Max Drawdown: {max_drawdown:.2f}%
//
// To replay exact entries, use: Tools → Import Trades in TradingView

"""


# ── Public API ────────────────────────────────────────────────


def strategy_to_pinescript(
    name: str,
    python_code: str = "",
    metadata: Optional[dict] = None,
) -> str:
    """
    Convert a saved Python strategy to Pine Script v5.

    Detects common indicator patterns in the Python code (MACD, RSI, Bollinger
    Bands, EMA) and generates matching Pine Script logic. Falls back to a
    generic SMA-crossover template when no known pattern is found.

    Args:
        name:        Strategy name (used in Pine title).
        python_code: Python source code of the strategy.
        metadata:    Optional dict with "description", "default_symbol", etc.

    Returns:
        Pine Script v5 string ready to paste into TradingView.
    """
    meta = metadata or {}
    description = meta.get("description", "Converted from Python strategy")
    today = datetime.now().strftime("%Y-%m-%d")

    # Detect indicator from Python code
    logic_block = _detect_indicator_block(python_code, name)

    pine = _PINE_HEADER.format(name=name, description=description, date=today)
    pine += logic_block
    pine += _PINE_ENTRIES
    pine += _PINE_TRADE_MARKERS

    return pine


def export_backtest_result_to_pinescript(result: Any) -> str:
    """
    Generate Pine Script with embedded backtest metadata from a BacktestResult.

    Includes a comment block with key performance metrics from the Python
    backtest run so the TradingView chart can be annotated.

    Args:
        result: engine.backtest.BacktestResult instance.

    Returns:
        Pine Script v5 string with backtest summary comment.
    """
    name = getattr(result, "strategy_name", "Unknown Strategy")
    symbol = getattr(result, "symbol", "")
    period = getattr(result, "period", "")
    total_return = getattr(result, "total_return", 0.0)
    sharpe = getattr(result, "sharpe_ratio", 0.0)
    win_rate = getattr(result, "win_rate", 0.0)
    max_dd = getattr(result, "max_drawdown", 0.0)
    trades = getattr(result, "trades", [])

    today = datetime.now().strftime("%Y-%m-%d")

    pine = _PINE_HEADER.format(
        name=name,
        description=f"Exported from Python backtest on {symbol} ({period})",
        date=today,
    )

    # Add backtest summary comment
    pine += _PINE_BACKTEST_TRADES.format(
        n_trades=len(trades),
        symbol=symbol,
        period=period,
        total_return=total_return,
        sharpe=sharpe,
        win_rate=win_rate,
        max_drawdown=max_dd,
    )

    pine += _PINE_GENERIC_LOGIC.format(strategy_name=name)
    pine += _PINE_ENTRIES
    pine += _PINE_TRADE_MARKERS

    return pine


def save_pinescript(pine: str, output_path: Path) -> None:
    """Write Pine Script string to a .pine file."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(pine, encoding="utf-8")


# ── Internal helpers ──────────────────────────────────────────


def _detect_indicator_block(python_code: str, strategy_name: str) -> str:
    """
    Heuristic: scan Python code for known indicator names and return the
    corresponding Pine Script logic block.
    """
    code_lower = python_code.lower()

    # Check for specific indicator usage — order matters (most specific first)
    if "macd" in code_lower:
        return _PINE_INPUT_BLOCK + _PINE_MACD_LOGIC
    if "rsi" in code_lower and "bollinger" not in code_lower:
        return _PINE_RSI_LOGIC
    if "bollinger" in code_lower or "bb(" in code_lower or "bbands" in code_lower:
        return _PINE_BB_LOGIC
    if "ema" in code_lower:
        return _PINE_EMA_LOGIC

    # Generic fallback
    return _PINE_GENERIC_LOGIC.format(strategy_name=strategy_name)
